CREATE TABLE IF NOT EXISTS STATUS (
	ID           INT(6)          NOT NULL AUTO_INCREMENT, 
	NAME         VARCHAR(250)    NOT NULL, 
	DESCRIPTION  VARCHAR(250)	NOT NULL,
	CREATED_AT   DATETIME,
	PRIMARY KEY (ID)
) ENGINE=InnoDB;